Cdh4u mish gunnar2
cdh4u/draft-datachannel-t140 pull request #29
Opened 2019-09-12 17:21 UTC by cdh4u

2019-09-12 21:20 UTC, gunnarhm commented on draft-ietf-mmusic-t140-usage-data-channel.xml
> +            The default maximum character transmission rate
No maximum character transmission rate applies.    That is stated in the draft.

(this is different from RFC 4103 that has 30 as default.)

2019-09-12 21:24 UTC, gunnarhm requested changes
Fine except the words about characters per second default to 30. It is not 30, it is no limit.

2019-09-13 01:36 UTC, cdh4u commented on draft-ietf-mmusic-t140-usage-data-channel.xml
> +            The default maximum character transmission rate
Correct. I will fix that.

2019-09-13 11:57 UTC, gunnarhm commented
looks good.

2019-09-13 19:14 UTC, merged